export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Marquee } from './Marquee'
export { default as ProblemSection } from './ProblemSection'
export { default as SolutionSection } from './SolutionSection'
export { default as TestimonialSection } from './TestimonialSection'
export { default as ContactSection } from './ContactSection'
export { default as Footer } from './Footer'
